// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 55.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'commercial_directory_users';

  static const String assets_ads_home_banner_png = 'assets/ads/home_banner.png';
  static const String commercial_directory_users$assets_ads_home_banner_png = 'packages/commercial_directory_users/assets/ads/home_banner.png';

  static const String assets_ads_home_banner_1_png = 'assets/ads/home_banner_1.png';
  static const String commercial_directory_users$assets_ads_home_banner_1_png = 'packages/commercial_directory_users/assets/ads/home_banner_1.png';

  static const String assets_ads_home_banner_2_png = 'assets/ads/home_banner_2.png';
  static const String commercial_directory_users$assets_ads_home_banner_2_png = 'packages/commercial_directory_users/assets/ads/home_banner_2.png';

  static const String assets_ads_home_banner_3_png = 'assets/ads/home_banner_3.png';
  static const String commercial_directory_users$assets_ads_home_banner_3_png = 'packages/commercial_directory_users/assets/ads/home_banner_3.png';

  static const String assets_ads_home_flash_png = 'assets/ads/home_flash.png';
  static const String commercial_directory_users$assets_ads_home_flash_png = 'packages/commercial_directory_users/assets/ads/home_flash.png';

  static const String assets_ads_sector_banner_png = 'assets/ads/sector_banner.png';
  static const String commercial_directory_users$assets_ads_sector_banner_png = 'packages/commercial_directory_users/assets/ads/sector_banner.png';

  static const String assets_ads_sector_banner_1_png = 'assets/ads/sector_banner_1.png';
  static const String commercial_directory_users$assets_ads_sector_banner_1_png = 'packages/commercial_directory_users/assets/ads/sector_banner_1.png';

  static const String assets_ads_sector_banner_2_png = 'assets/ads/sector_banner_2.png';
  static const String commercial_directory_users$assets_ads_sector_banner_2_png = 'packages/commercial_directory_users/assets/ads/sector_banner_2.png';

  static const String assets_ads_sector_banner_3_png = 'assets/ads/sector_banner_3.png';
  static const String commercial_directory_users$assets_ads_sector_banner_3_png = 'packages/commercial_directory_users/assets/ads/sector_banner_3.png';

  static const String assets_google_fonts_Cairo_VariableFont_slnt_wght_ttf = 'assets/google_fonts/Cairo-VariableFont_slnt,wght.ttf';
  static const String commercial_directory_users$assets_google_fonts_Cairo_VariableFont_slnt_wght_ttf = 'packages/commercial_directory_users/assets/google_fonts/Cairo-VariableFont_slnt,wght.ttf';

  static const String assets_home_bottom_icons_fav_svg = 'assets/home_bottom_icons/fav.svg';
  static const String commercial_directory_users$assets_home_bottom_icons_fav_svg = 'packages/commercial_directory_users/assets/home_bottom_icons/fav.svg';

  static const String assets_home_bottom_icons_favorite_active_svg = 'assets/home_bottom_icons/favorite_active.svg';
  static const String commercial_directory_users$assets_home_bottom_icons_favorite_active_svg = 'packages/commercial_directory_users/assets/home_bottom_icons/favorite_active.svg';

  static const String assets_home_bottom_icons_home_svg = 'assets/home_bottom_icons/home.svg';
  static const String commercial_directory_users$assets_home_bottom_icons_home_svg = 'packages/commercial_directory_users/assets/home_bottom_icons/home.svg';

  static const String assets_home_bottom_icons_home_active_svg = 'assets/home_bottom_icons/home_active.svg';
  static const String commercial_directory_users$assets_home_bottom_icons_home_active_svg = 'packages/commercial_directory_users/assets/home_bottom_icons/home_active.svg';

  static const String assets_home_bottom_icons_sectore_svg = 'assets/home_bottom_icons/sectore.svg';
  static const String commercial_directory_users$assets_home_bottom_icons_sectore_svg = 'packages/commercial_directory_users/assets/home_bottom_icons/sectore.svg';

  static const String assets_home_bottom_icons_sectore_active_svg = 'assets/home_bottom_icons/sectore_active.svg';
  static const String commercial_directory_users$assets_home_bottom_icons_sectore_active_svg = 'packages/commercial_directory_users/assets/home_bottom_icons/sectore_active.svg';

  static const String assets_home_bottom_icons_user_svg = 'assets/home_bottom_icons/user.svg';
  static const String commercial_directory_users$assets_home_bottom_icons_user_svg = 'packages/commercial_directory_users/assets/home_bottom_icons/user.svg';

  static const String assets_home_bottom_icons_user_active_svg = 'assets/home_bottom_icons/user_active.svg';
  static const String commercial_directory_users$assets_home_bottom_icons_user_active_svg = 'packages/commercial_directory_users/assets/home_bottom_icons/user_active.svg';

  static const String assets_icons_aggression_svg = 'assets/icons/aggression.svg';
  static const String commercial_directory_users$assets_icons_aggression_svg = 'packages/commercial_directory_users/assets/icons/aggression.svg';

  static const String assets_icons_apple_icon_svg = 'assets/icons/apple_icon.svg';
  static const String commercial_directory_users$assets_icons_apple_icon_svg = 'packages/commercial_directory_users/assets/icons/apple_icon.svg';

  static const String assets_icons_authentication_svg = 'assets/icons/authentication.svg';
  static const String commercial_directory_users$assets_icons_authentication_svg = 'packages/commercial_directory_users/assets/icons/authentication.svg';

  static const String assets_icons_awesome_share_svg = 'assets/icons/awesome-share.svg';
  static const String commercial_directory_users$assets_icons_awesome_share_svg = 'packages/commercial_directory_users/assets/icons/awesome-share.svg';

  static const String assets_icons_c_phone_svg = 'assets/icons/c_phone.svg';
  static const String commercial_directory_users$assets_icons_c_phone_svg = 'packages/commercial_directory_users/assets/icons/c_phone.svg';

  static const String assets_icons_edit_svg = 'assets/icons/edit.svg';
  static const String commercial_directory_users$assets_icons_edit_svg = 'packages/commercial_directory_users/assets/icons/edit.svg';

  static const String assets_icons_error_svg = 'assets/icons/error.svg';
  static const String commercial_directory_users$assets_icons_error_svg = 'packages/commercial_directory_users/assets/icons/error.svg';

  static const String assets_icons_facebook_svg = 'assets/icons/facebook.svg';
  static const String commercial_directory_users$assets_icons_facebook_svg = 'packages/commercial_directory_users/assets/icons/facebook.svg';

  static const String assets_icons_facebook_icon_svg = 'assets/icons/facebook_icon.svg';
  static const String commercial_directory_users$assets_icons_facebook_icon_svg = 'packages/commercial_directory_users/assets/icons/facebook_icon.svg';

  static const String assets_icons_fav_svg = 'assets/icons/fav.svg';
  static const String commercial_directory_users$assets_icons_fav_svg = 'packages/commercial_directory_users/assets/icons/fav.svg';

  static const String assets_icons_fav_filled_svg = 'assets/icons/fav_filled.svg';
  static const String commercial_directory_users$assets_icons_fav_filled_svg = 'packages/commercial_directory_users/assets/icons/fav_filled.svg';

  static const String assets_icons_g_mode_svg = 'assets/icons/g_mode.svg';
  static const String commercial_directory_users$assets_icons_g_mode_svg = 'packages/commercial_directory_users/assets/icons/g_mode.svg';

  static const String assets_icons_google_icon_svg = 'assets/icons/google_icon.svg';
  static const String commercial_directory_users$assets_icons_google_icon_svg = 'packages/commercial_directory_users/assets/icons/google_icon.svg';

  static const String assets_icons_instagram_svg = 'assets/icons/instagram.svg';
  static const String commercial_directory_users$assets_icons_instagram_svg = 'packages/commercial_directory_users/assets/icons/instagram.svg';

  static const String assets_icons_language_svg = 'assets/icons/language.svg';
  static const String commercial_directory_users$assets_icons_language_svg = 'packages/commercial_directory_users/assets/icons/language.svg';

  static const String assets_icons_linkedin_svg = 'assets/icons/linkedin.svg';
  static const String commercial_directory_users$assets_icons_linkedin_svg = 'packages/commercial_directory_users/assets/icons/linkedin.svg';

  static const String assets_icons_login_first_svg = 'assets/icons/login_first.svg';
  static const String commercial_directory_users$assets_icons_login_first_svg = 'packages/commercial_directory_users/assets/icons/login_first.svg';

  static const String assets_icons_network_error_svg = 'assets/icons/network_error.svg';
  static const String commercial_directory_users$assets_icons_network_error_svg = 'packages/commercial_directory_users/assets/icons/network_error.svg';

  static const String assets_icons_no_data_svg = 'assets/icons/no_data.svg';
  static const String commercial_directory_users$assets_icons_no_data_svg = 'packages/commercial_directory_users/assets/icons/no_data.svg';

  static const String assets_icons_person_png = 'assets/icons/person.png';
  static const String commercial_directory_users$assets_icons_person_png = 'packages/commercial_directory_users/assets/icons/person.png';

  static const String assets_icons_saudi_arabia_png = 'assets/icons/saudi_arabia.png';
  static const String commercial_directory_users$assets_icons_saudi_arabia_png = 'packages/commercial_directory_users/assets/icons/saudi_arabia.png';

  static const String assets_icons_searching_svg = 'assets/icons/searching.svg';
  static const String commercial_directory_users$assets_icons_searching_svg = 'packages/commercial_directory_users/assets/icons/searching.svg';

  static const String assets_icons_services_png = 'assets/icons/services.png';
  static const String commercial_directory_users$assets_icons_services_png = 'packages/commercial_directory_users/assets/icons/services.png';

  static const String assets_icons_share_svg = 'assets/icons/share.svg';
  static const String commercial_directory_users$assets_icons_share_svg = 'packages/commercial_directory_users/assets/icons/share.svg';

  static const String assets_icons_tiktok_svg = 'assets/icons/tiktok.svg';
  static const String commercial_directory_users$assets_icons_tiktok_svg = 'packages/commercial_directory_users/assets/icons/tiktok.svg';

  static const String assets_icons_twitter_svg = 'assets/icons/twitter.svg';
  static const String commercial_directory_users$assets_icons_twitter_svg = 'packages/commercial_directory_users/assets/icons/twitter.svg';

  static const String assets_icons_usa_png = 'assets/icons/usa.png';
  static const String commercial_directory_users$assets_icons_usa_png = 'packages/commercial_directory_users/assets/icons/usa.png';

  static const String assets_icons_v_mode_svg = 'assets/icons/v_mode.svg';
  static const String commercial_directory_users$assets_icons_v_mode_svg = 'packages/commercial_directory_users/assets/icons/v_mode.svg';

  static const String assets_icons_whatsapp_svg = 'assets/icons/whatsapp.svg';
  static const String commercial_directory_users$assets_icons_whatsapp_svg = 'packages/commercial_directory_users/assets/icons/whatsapp.svg';

  static const String assets_icons_youtube_svg = 'assets/icons/youtube.svg';
  static const String commercial_directory_users$assets_icons_youtube_svg = 'packages/commercial_directory_users/assets/icons/youtube.svg';

  static const String assets_onboarding_email_confirmation_svg = 'assets/onboarding/email_confirmation.svg';
  static const String commercial_directory_users$assets_onboarding_email_confirmation_svg = 'packages/commercial_directory_users/assets/onboarding/email_confirmation.svg';

  static const String assets_onboarding_onboarding_1_svg = 'assets/onboarding/onboarding_1.svg';
  static const String commercial_directory_users$assets_onboarding_onboarding_1_svg = 'packages/commercial_directory_users/assets/onboarding/onboarding_1.svg';

  static const String assets_onboarding_onboarding_2_svg = 'assets/onboarding/onboarding_2.svg';
  static const String commercial_directory_users$assets_onboarding_onboarding_2_svg = 'packages/commercial_directory_users/assets/onboarding/onboarding_2.svg';

  static const String assets_onboarding_onboarding_3_svg = 'assets/onboarding/onboarding_3.svg';
  static const String commercial_directory_users$assets_onboarding_onboarding_3_svg = 'packages/commercial_directory_users/assets/onboarding/onboarding_3.svg';

  static const String assets_splash_splash_screen_png = 'assets/splash/splash_screen.png';
  static const String commercial_directory_users$assets_splash_splash_screen_png = 'packages/commercial_directory_users/assets/splash/splash_screen.png';

  static const String assets_translations_ar_json = 'assets/translations/ar.json';
  static const String commercial_directory_users$assets_translations_ar_json = 'packages/commercial_directory_users/assets/translations/ar.json';

  static const String assets_translations_en_json = 'assets/translations/en.json';
  static const String commercial_directory_users$assets_translations_en_json = 'packages/commercial_directory_users/assets/translations/en.json';
}
