// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1__460Nq8LNCz_jCREriELRAGZMMHfc',
    appId: '1:423520422471:android:39b7ec4bcd9207e4c8ff62',
    messagingSenderId: '423520422471',
    projectId: 'gogesh-74c2c',
    storageBucket: 'gogesh-74c2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFEItGc2ho7qVBz4sxe6_YOC_IXt2Svp4',
    appId: '1:423520422471:ios:febd0160f82e051dc8ff62',
    messagingSenderId: '423520422471',
    projectId: 'gogesh-74c2c',
    storageBucket: 'gogesh-74c2c.appspot.com',
    androidClientId: '423520422471-249pfgb9c7nn66511odolbv28slg5957.apps.googleusercontent.com',
    iosClientId: '423520422471-6cfqoh5vsn8o4a2m01tutjc0euqrks1t.apps.googleusercontent.com',
    iosBundleId: 'com.gogesh.users',
  );
}
