import 'package:commercial_directory_users/domain/entities/activity_entity.dart';
import 'package:commercial_directory_users/domain/entities/sector_entity.dart';
import 'package:commercial_directory_users/domain/entities/season_entity.dart';
import 'package:commercial_directory_users/domain/entities/specialization_entity.dart';
import 'package:commercial_directory_users/domain/entities/offer/offer_entity.dart';

// final offers = <Offer>[
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
//   Offer(
//       id: 1,
//       name: "first",
//       description:
//           "offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description offer description ",
//       constraints:
//           "offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints offer constraints ",
//       image: "image",
//       views: 40,
//       price: 12.43,
//       total: 32.43,
//       bold: true,
//       category: const Category(name: "Category one", id: 1),
//       specialization: Specialization(name: "Specialization one", id: 1),
//       activity: Activity(name: "Activity one", id: 1),
//       season: Season(name: "Seasson One", id: 1),
//       occasion: Occasion(name: "Occasion one", id: 1)),
// ];
